[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "runner"
path = "src/runner.rs"

[dependencies.backend]
path = "../backend"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
bytemuck = { version = "1.4", features = ["derive"] }
wgpu = { workspace = true }
winit = { workspace = true }
ultraviolet = { version = "0.9.2", features = ["bytemuck"] }

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4.30"