[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "runner"
path = "src/runner.rs"

[dependencies.backend]
path = "../backend"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
wgpu = { version = "0.19.3", features = ["webgl"] }
winit = { workspace = true }
bytemuck = { version = "1.4", features = ["derive"] }
ultraviolet = { version = "0.9.2", features = ["bytemuck"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3.0"
simple_logger = "4.3.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.45"
wasm-bindgen-futures = "0.4.30"
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.5"