[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies.app]
path = "../app"

[dependencies.backend]
path = "../backend"